pipeline {
    agent any

    stages {

        stage('Clone') {
            steps {
                git 'https://github.com/isha-patel-14/Sem4-Practical.git'
            }
        }

        stage('Build') {
            steps {
                dir('demo-jenkins-pipeline-main') {
                    sh 'javac index.java'
                }
            }
        }

        stage('Test') {
            steps {
                dir('demo-jenkins-pipeline-main') {
                    sh 'java index'
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}