pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                dir('demo-jenkins-pipeline-main') {
                    bat 'javac index.java'
                }
            }
        }

        stage('Test') {
            steps {
                dir('demo-jenkins-pipeline-main') {
                    bat 'java index'
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}